import { v4 as uuidv4 } from 'uuid';

export const getDefaultDashboardLayout = () => {
  const pageId = uuidv4();
  
  return {
    widgets: [
      {
        id: uuidv4(),
        type: 'clock',
        name: 'clock',
        iconUrl: '',
        grid: { x: 2, y: 0, w: 4, h: 2 },
        pageId: pageId,
        config: { showCityName: true },
      },
      {
        id: uuidv4(),
        type: 'weather',
        name: 'weather',
        iconUrl: '',
        grid: { x: 0, y: 0, w: 2, h: 2 },
        pageId: pageId,
        config: { view: 'daily' },
        widgetType: 'weather',
        syncConfig: true,
      },
      {
        id: uuidv4(),
        type: 'search',
        name: 'search',
        iconUrl: '',
        grid: { x: 2, y: 2, w: 4, h: 1 },
        pageId: pageId,
        config: {},
      },
      {
        id: uuidv4(),
        type: 'calendar',
        name: 'calendar',
        iconUrl: '',
        grid: { x: 0, y: 2, w: 2, h: 3 },
        pageId: pageId,
        config: {},
      },
      {
        id: uuidv4(),
        type: 'rss',
        name: 'rss',
        iconUrl: '',
        grid: { x: 6, y: 0, w: 2, h: 5 },
        pageId: pageId,
        config: {
          feedUrls: ['https://selfh.st/rss/'],
          feedUrl: 'https://selfh.st/rss/',
          maxItems: 20,
          refreshInterval: 20,
        },
        widgetType: 'rss',
        syncConfig: true,
      },
      {
        id: uuidv4(),
        type: 'shortcut',
        name: 'Youtube',
        url: 'https://youtube.com',
        iconUrl: '',
        internalUrl: '',
        isSelfHosted: false,
        grid: { x: 2, y: 3, w: 1, h: 1 },
        pageId: pageId,
      },
      {
        id: uuidv4(),
        type: 'shortcut',
        name: 'IMDB',
        url: 'https://imdb.com',
        iconUrl: '',
        internalUrl: '',
        isSelfHosted: false,
        grid: { x: 3, y: 3, w: 1, h: 1 },
        pageId: pageId,
      },
      {
        id: uuidv4(),
        type: 'shortcut',
        name: 'Reddit',
        url: 'https://reddit.com',
        iconUrl: '',
        internalUrl: '',
        isSelfHosted: false,
        grid: { x: 4, y: 3, w: 1, h: 1 },
        pageId: pageId,
      },
      {
        id: uuidv4(),
        type: 'shortcut',
        name: 'Github',
        url: 'https://github.com',
        iconUrl: '',
        internalUrl: '',
        isSelfHosted: false,
        grid: { x: 5, y: 3, w: 1, h: 1 },
        pageId: pageId,
      },
    ],
    pages: [{ id: pageId }],
    scrollDirection: 'vertical',
    defaultPageId: pageId,
    settings: {
      behavior: {
        refreshInterval: 10,
        autoDetectLocation: true,
        confirmEdit: false,
        autoSave: true,
      },
      display: {
        is24Hour: true,
        temperatureUnit: 'C',
        timezone: 'Europe/Stockholm',
        city: {
          name: 'Stockholm',
          country: '',
          timezone: 'Europe/Stockholm',
          latitude: 0,
          longitude: 0,
          abbreviation: 'STO',
        },
        dateFormat: 'DD/MM',
        language: 'en',
        location: '',
      },
      shortcuts: {
        toggleEdit: 'Alt+E',
        openSettings: 'Alt+,',
        addItem: 'Alt+N',
        saveChanges: 'Alt+S',
        prevPage: 'Alt+ArrowLeft',
        nextPage: 'Alt+ArrowRight',
      },
    },
  };
};

