export const TIMEZONES = [
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  
  // Europe
  { value: "Europe/London", label: "London (GMT/BST)" },
  { value: "Europe/Paris", label: "Paris (CET/CEST)" },
  { value: "Europe/Berlin", label: "Berlin (CET/CEST)" },
  { value: "Europe/Rome", label: "Rome (CET/CEST)" },
  { value: "Europe/Madrid", label: "Madrid (CET/CEST)" },
  { value: "Europe/Amsterdam", label: "Amsterdam (CET/CEST)" },
  { value: "Europe/Brussels", label: "Brussels (CET/CEST)" },
  { value: "Europe/Stockholm", label: "Stockholm (CET/CEST)" },
  { value: "Europe/Oslo", label: "Oslo (CET/CEST)" },
  { value: "Europe/Copenhagen", label: "Copenhagen (CET/CEST)" },
  { value: "Europe/Helsinki", label: "Helsinki (EET/EEST)" },
  { value: "Europe/Vienna", label: "Vienna (CET/CEST)" },
  { value: "Europe/Zurich", label: "Zurich (CET/CEST)" },
  { value: "Europe/Prague", label: "Prague (CET/CEST)" },
  { value: "Europe/Warsaw", label: "Warsaw (CET/CEST)" },
  { value: "Europe/Budapest", label: "Budapest (CET/CEST)" },
  { value: "Europe/Athens", label: "Athens (EET/EEST)" },
  { value: "Europe/Istanbul", label: "Istanbul (TRT)" },
  { value: "Europe/Moscow", label: "Moscow (MSK)" },
  { value: "Europe/Kiev", label: "Kiev (EET/EEST)" },
  
  // Americas
  { value: "America/New_York", label: "New York (Eastern Time)" },
  { value: "America/Chicago", label: "Chicago (Central Time)" },
  { value: "America/Denver", label: "Denver (Mountain Time)" },
  { value: "America/Los_Angeles", label: "Los Angeles (Pacific Time)" },
  { value: "America/Phoenix", label: "Phoenix (MST)" },
  { value: "America/Anchorage", label: "Anchorage (Alaska Time)" },
  { value: "America/Honolulu", label: "Honolulu (Hawaii Time)" },
  { value: "America/Toronto", label: "Toronto (Eastern Time)" },
  { value: "America/Vancouver", label: "Vancouver (Pacific Time)" },
  { value: "America/Montreal", label: "Montreal (Eastern Time)" },
  { value: "America/Sao_Paulo", label: "Sao Paulo (Brasilia Time)" },
  { value: "America/Mexico_City", label: "Mexico City (Central Time)" },
  
  // Asia
  { value: "Asia/Tokyo", label: "Tokyo (JST)" },
  { value: "Asia/Shanghai", label: "Shanghai (CST)" },
  { value: "Asia/Hong_Kong", label: "Hong Kong (HKT)" },
  { value: "Asia/Seoul", label: "Seoul (KST)" },
  { value: "Asia/Singapore", label: "Singapore (SGT)" },
  { value: "Asia/Bangkok", label: "Bangkok (ICT)" },
  { value: "Asia/Dubai", label: "Dubai (GST)" },
  { value: "Asia/Kolkata", label: "Kolkata (IST)" },
  { value: "Asia/Jakarta", label: "Jakarta (WIB)" },
  { value: "Asia/Taipei", label: "Taipei (CST)" },
  { value: "Asia/Manila", label: "Manila (PHT)" },
  
  // Oceania
  { value: "Australia/Sydney", label: "Sydney (AEST/AEDT)" },
  { value: "Australia/Melbourne", label: "Melbourne (AEST/AEDT)" },
  { value: "Australia/Brisbane", label: "Brisbane (AEST)" },
  { value: "Australia/Perth", label: "Perth (AWST)" },
  { value: "Australia/Adelaide", label: "Adelaide (ACST/ACDT)" },
  { value: "Pacific/Auckland", label: "Auckland (NZST/NZDT)" },
  { value: "Pacific/Fiji", label: "Fiji (FJT/FJST)" },
  
  // Africa
  { value: "Africa/Cairo", label: "Cairo (EET/EEST)" },
  { value: "Africa/Johannesburg", label: "Johannesburg (SAST)" },
  { value: "Africa/Lagos", label: "Lagos (WAT)" },
  { value: "Africa/Nairobi", label: "Nairobi (EAT)" },
];

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "China",
  "India",
  "Brazil",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Poland",
  "Russia",
  "South Korea",
  "Singapore",
  "New Zealand",
  "Ireland",
  "Portugal",
  "Greece",
  "Turkey",
  "South Africa",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Thailand",
  "Vietnam",
  "Indonesia",
  "Malaysia",
  "Philippines",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Ukraine",
  "Pakistan",
  "Bangladesh",
];

export const LOCALE_TO_COUNTRY: Record<string, string> = {
  'en-US': 'United States',
  'en-GB': 'United Kingdom',
  'en-CA': 'Canada',
  'en-AU': 'Australia',
  'fr-FR': 'France',
  'de-DE': 'Germany',
  'ja-JP': 'Japan',
  'sv-SE': 'Sweden',
  'es-ES': 'Spain',
  'it-IT': 'Italy',
  'pt-BR': 'Brazil',
  'nl-NL': 'Netherlands',
  'ru-RU': 'Russia',
  'zh-CN': 'China',
  'ko-KR': 'South Korea',
  'es-MX': 'Mexico',
  'da-DK': 'Denmark',
  'no-NO': 'Norway',
  'fi-FI': 'Finland',
  'pl-PL': 'Poland',
  'tr-TR': 'Turkey',
  'pt-PT': 'Portugal',
  'el-GR': 'Greece',
  'id-ID': 'Indonesia',
  'th-TH': 'Thailand',
  'vi-VN': 'Vietnam',
  'ar-EG': 'Egypt',
  'hi-IN': 'India'
};

export const extractCityFromTimezone = (timezone: string): string => {
  if (!timezone) return '';
  const parts = timezone.split('/');
  if (parts.length > 1) {
    return parts[parts.length - 1].replace(/_/g, ' ');
  }
  return timezone;
};

export const TIMEZONE_TO_COUNTRY: Record<string, string> = {
  "Europe/London": "United Kingdom",
  "Europe/Paris": "France",
  "Europe/Berlin": "Germany",
  "Europe/Rome": "Italy",
  "Europe/Madrid": "Spain",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Brussels": "Belgium",
  "Europe/Stockholm": "Sweden",
  "Europe/Oslo": "Norway",
  "Europe/Copenhagen": "Denmark",
  "Europe/Helsinki": "Finland",
  "Europe/Vienna": "Austria",
  "Europe/Zurich": "Switzerland",
  "Europe/Prague": "Czech Republic",
  "Europe/Warsaw": "Poland",
  "Europe/Budapest": "Hungary",
  "Europe/Athens": "Greece",
  "Europe/Istanbul": "Turkey",
  "Europe/Moscow": "Russia",
  "Europe/Kiev": "Ukraine",
  "America/New_York": "United States",
  "America/Chicago": "United States",
  "America/Denver": "United States",
  "America/Los_Angeles": "United States",
  "America/Phoenix": "United States",
  "America/Anchorage": "United States",
  "America/Honolulu": "United States",
  "America/Toronto": "Canada",
  "America/Vancouver": "Canada",
  "America/Montreal": "Canada",
  "America/Sao_Paulo": "Brazil",
  "America/Mexico_City": "Mexico",
  "Asia/Tokyo": "Japan",
  "Asia/Shanghai": "China",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Seoul": "South Korea",
  "Asia/Singapore": "Singapore",
  "Asia/Bangkok": "Thailand",
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Kolkata": "India",
  "Asia/Jakarta": "Indonesia",
  "Asia/Taipei": "Taiwan",
  "Asia/Manila": "Philippines",
  "Australia/Sydney": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Adelaide": "Australia",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Fiji": "Fiji",
  "Africa/Cairo": "Egypt",
  "Africa/Johannesburg": "South Africa",
  "Africa/Lagos": "Nigeria",
  "Africa/Nairobi": "Kenya"
};
